Here is a demo for calibartion the Dual-Rotating Retarder Polarimeter that requires a measurement of air and a best fit using the Mueller matrix model. One advantage of this method is that none of the optical components (aside from the sample) need to be removed for calibration. Ideally, this procedure will correct for imperfections in the optical components including waveplate retardance, linear polarizer alignment, and waveplate fast axis angle. 

In [1]:
import numpy as np

The basic idea behind this method is to create a realistic Mueller matrix model for the DRRP without having to individually measure the Mueller matrix of each component. We could assume ideal matrices for each component, but in reality there will be small imperfections and misalignments that can increase the uncertainty in measurements if not corrected for. 

Using the DRRP requires three key components, a matrix model for the system, a Mueller matrix for the sample, and measurements taken of the sample. This can be written as:
$$M_{system}I_{measured} = M_{sample}$$
For calibration, we want to find $M_{system}$ from known $I_{measured}$ and $M_{sample}$. By taking measurements of air, we can replace $M_{sample}$ with the identity matrix: 

In [3]:
print(np.identity(4))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
